//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontonisAG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikel()
        {
            this.Bestelldetails = new HashSet<Bestelldetails>();
        }
    
        public long Artikel_Nr { get; set; }
        public string Artikelname { get; set; }
        public long Lieferanten_Nr { get; set; }
        public long Kategorie_Nr { get; set; }
        public string Liefereinheit { get; set; }
        public decimal Einzelpreis { get; set; }
        public long Lagerbestand { get; set; }
        public long BestellteEinheiten { get; set; }
        public long Mindestbestand { get; set; }
        public long Auslaufartikel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelldetails> Bestelldetails { get; set; }
        public virtual Kategorien Kategorien { get; set; }
        public virtual Lieferanten Lieferanten { get; set; }
    }
}
