//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontonisAG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellungen
    {
        public long Bestell_Nr { get; set; }
        public long Kunden_Code { get; set; }
        public long Personal_Nr { get; set; }
        public string Bestelldatum { get; set; }
        public string Lieferdatum { get; set; }
        public string Versanddatum { get; set; }
        public long Versand_Über { get; set; }
        public decimal Frachtkosten { get; set; }
        public string Empfänger { get; set; }
        public string Straße { get; set; }
        public string Ort { get; set; }
        public string Region { get; set; }
        public string PLZ { get; set; }
        public string Bestimmungsland { get; set; }
    
        public virtual Bestelldetails Bestelldetails { get; set; }
        public virtual Kunden Kunden { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Versandfirmen Versandfirmen { get; set; }
    }
}
