//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontonisAG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelldetails
    {
        public long Bestell_Nr { get; set; }
        public long Artikel_Nr { get; set; }
        public decimal Einzelpreis { get; set; }
        public long Anzahl { get; set; }
        public decimal Rabatt { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Bestellungen Bestellungen { get; set; }
    }
}
