//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontonisAG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KontonisAGEntities : DbContext
    {
        public KontonisAGEntities()
            : base("name=KontonisAGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikel> Artikel { get; set; }
        public virtual DbSet<Bestelldetails> Bestelldetails { get; set; }
        public virtual DbSet<Bestellungen> Bestellungen { get; set; }
        public virtual DbSet<Kategorien> Kategorien { get; set; }
        public virtual DbSet<Kunden> Kunden { get; set; }
        public virtual DbSet<Lieferanten> Lieferanten { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Versandfirmen> Versandfirmen { get; set; }
    }
}
