//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontonisAG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Bestellungen = new HashSet<Bestellungen>();
        }
    
        public long Personal_Nr { get; set; }
        public string Nachname { get; set; }
        public string Vorname { get; set; }
        public string Position { get; set; }
        public string Anrede { get; set; }
        public string Geburtsdatum { get; set; }
        public string Einstellung { get; set; }
        public string Straße { get; set; }
        public string Ort { get; set; }
        public string Region { get; set; }
        public string PLZ { get; set; }
        public string Land { get; set; }
        public string Telefon_Privat { get; set; }
        public string Durchwahl_Büro { get; set; }
        public string Foto { get; set; }
        public string Bemerkungen { get; set; }
        public string Vorgesetzte_r_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestellungen> Bestellungen { get; set; }
    }
}
